development:
  adapter: postgresql
  database: rapidfire_demo_development
  host: localhost
  pool: 5
  timeout: 6000

test: &test
  adapter: postgresql
  database: rapidfire_demo_test
  pool: 5
  timeout: 6000

production:
  adapter: postgresql
  database: rapidfire_demo_production
  pool: 5
  timeout: 6000
